2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Configure stats pid to 303516
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Loading settings from /home/vador/.config/wandb/settings
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Loading settings from /home/vador/git/chessGPT/notebooks/wandb/settings
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-08 13:06:53,395 INFO    MainThread:303516 [wandb_init.py:_log_setup():507] Logging user logs to /home/vador/git/chessGPT/notebooks/wandb/run-20230608_130653-v3kgcbj2/logs/debug.log
2023-06-08 13:06:53,396 INFO    MainThread:303516 [wandb_init.py:_log_setup():508] Logging internal logs to /home/vador/git/chessGPT/notebooks/wandb/run-20230608_130653-v3kgcbj2/logs/debug-internal.log
2023-06-08 13:06:53,396 INFO    MainThread:303516 [wandb_init.py:init():547] calling init triggers
2023-06-08 13:06:53,396 INFO    MainThread:303516 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-08 13:06:53,396 INFO    MainThread:303516 [wandb_init.py:init():571] re-initializing run, found existing run on stack: 54pdefwn
2023-06-08 13:06:53,397 INFO    MainThread:303516 [wandb_run.py:_finish():1890] finishing run vador/chessGPT/54pdefwn
2023-06-08 13:06:53,398 ERROR   MainThread:303516 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-06-08 13:06:53,398 INFO    MainThread:303516 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-08 13:06:53,398 INFO    MainThread:303516 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-06-08 13:06:53,398 INFO    MainThread:303516 [wandb_run.py:_atexit_cleanup():2124] got exitcode: 0
2023-06-08 13:06:53,398 INFO    MainThread:303516 [wandb_run.py:_restore():2107] restore
2023-06-08 13:06:53,398 INFO    MainThread:303516 [wandb_run.py:_restore():2113] restore done
2023-06-08 13:11:11,077 INFO    MainThread:303516 [wandb_init.py:init():596] starting backend
2023-06-08 13:11:11,077 INFO    MainThread:303516 [wandb_init.py:init():600] setting up manager
2023-06-08 13:11:11,079 INFO    MainThread:303516 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-08 13:11:11,080 INFO    MainThread:303516 [wandb_init.py:init():606] backend started and connected
2023-06-08 13:11:11,082 INFO    MainThread:303516 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-06-08 13:11:11,082 INFO    MainThread:303516 [wandb_run.py:_label_probe_notebook():1245] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-06-08 13:11:11,082 INFO    MainThread:303516 [wandb_init.py:init():703] updated telemetry
2023-06-08 13:11:11,088 INFO    MainThread:303516 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
